"""Heartbeat & Liveness Management for Hierarchical UAV Swarm Network.

Implements continuous 1-hop heartbeat emission, link quality monitoring, and node
liveness tracking across the UAV swarm:
    1. Periodically transmits encrypted ``HeartbeatMessage`` datagrams via a one-shot
       ``threading.Timer`` chain (default 1.0 s interval).
    2. Processes inbound heartbeats, updating monotonic ``last_seen`` timestamps,
       sequence numbers, and link metrics ($O(1)$ dictionary lookups).
    3. Periodically audits node health using ``time.monotonic()``. If a node stays silent
       longer than ``heartbeat_timeout_sec`` (default 3.0 s / 3 missed cycles):
         - Marks the node ``UNREACHABLE`` in ``topology.py``.
         - Invokes ``security.expire_session(drone_id)`` to purge zeroised session keys.
         - Emits ``NODE_TIMEOUT`` and ``SESSION_EXPIRED`` events for downstream failover.

Thread Safety:
    All liveness states and internal event queues are protected by a single
    ``threading.RLock`` (`_lock`). Network I/O operations and downstream callbacks are
    executed outside of critical lock sections to prevent deadlocks.
"""

from __future__ import annotations

import logging
import os
import threading
import time
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Callable, Dict, List, Optional, Tuple

from hierarchical_swarm.messages import HeartbeatMessage
from hierarchical_swarm.node import NodeStatus, SwarmNode
from hierarchical_swarm.security import SwarmSecurityManager
from hierarchical_swarm.topology import SwarmTopology

try:
    from core.config import CONFIG
    _HEARTBEAT_INTERVAL: float = float(CONFIG.get("SWARM_HEARTBEAT_INTERVAL", 1.0))
    _HEARTBEAT_TIMEOUT: float = float(CONFIG.get("SWARM_HEARTBEAT_TIMEOUT", 3.0))
    _CHECK_INTERVAL: float = float(CONFIG.get("SWARM_CHECK_INTERVAL", 0.2))
except Exception:
    _HEARTBEAT_INTERVAL = float(os.getenv("SWARM_HEARTBEAT_INTERVAL", "1.0"))
    _HEARTBEAT_TIMEOUT = float(os.getenv("SWARM_HEARTBEAT_TIMEOUT", "3.0"))
    _CHECK_INTERVAL = float(os.getenv("SWARM_CHECK_INTERVAL", "0.2"))

try:
    from core.logging_utils import METRICS, get_logger
    _logger = get_logger("hierarchical_swarm.heartbeat")
except ImportError:
    _logger = logging.getLogger("hierarchical_swarm.heartbeat")
    METRICS = None


# ---------------------------------------------------------------------------
# Events & Configuration
# ---------------------------------------------------------------------------

class HeartbeatEventType(Enum):
    """Lifecycle events generated by HeartbeatManager."""

    HEARTBEAT_SENT     = auto()
    HEARTBEAT_RECEIVED = auto()
    NODE_TIMEOUT       = auto()
    SESSION_EXPIRED    = auto()
    NODE_RECOVERED     = auto()


@dataclass(slots=True, frozen=True)
class HeartbeatEvent:
    """An immutable event record produced by HeartbeatManager."""

    event_type: HeartbeatEventType
    drone_id:   str = ""
    extra:      str = ""


@dataclass(slots=True, frozen=True)
class HeartbeatConfig:
    """Runtime configuration for heartbeat emission and liveness auditing."""

    interval_sec:      float = _HEARTBEAT_INTERVAL
    timeout_sec:       float = _HEARTBEAT_TIMEOUT
    check_interval_sec: float = _CHECK_INTERVAL
    max_missed:        int   = 3

    @classmethod
    def from_env(cls) -> HeartbeatConfig:
        """Constructs a config instance reading environment defaults."""
        return cls(
            interval_sec=float(os.getenv("SWARM_HEARTBEAT_INTERVAL", str(_HEARTBEAT_INTERVAL))),
            timeout_sec=float(os.getenv("SWARM_HEARTBEAT_TIMEOUT", str(_HEARTBEAT_TIMEOUT))),
            check_interval_sec=float(os.getenv("SWARM_CHECK_INTERVAL", str(_CHECK_INTERVAL))),
            max_missed=int(os.getenv("SWARM_MAX_MISSED", "3")),
        )


# ---------------------------------------------------------------------------
# Liveness State
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class NodeLivenessState:
    """Runtime liveness tracking for a single monitored neighbor node."""

    drone_id:       str
    last_seen:      float = field(default_factory=time.monotonic)
    last_sequence:  int   = -1
    missed_count:   int   = 0
    total_received: int   = 0
    total_dropped:  int   = 0
    is_unreachable: bool  = False
    rtt_estimate:   float = 0.0


# ---------------------------------------------------------------------------
# Heartbeat Manager
# ---------------------------------------------------------------------------

class HeartbeatManager:
    """Manages periodic heartbeat generation, incoming message processing, and timeout detection.

    Args:
        local_node: The ``SwarmNode`` representing this drone.
        topology: Shared ``SwarmTopology`` instance.
        security: ``SwarmSecurityManager`` instance for session expiration & encryption.
        config: Optional ``HeartbeatConfig`` (defaults to `HeartbeatConfig.from_env()`).
        send_transport: Optional callable for transmitting encoded bytes `(bytes) -> None`.
        battery_fn: Optional callable returning current battery percentage `() -> float`.
    """

    def __init__(
        self,
        local_node:     SwarmNode,
        topology:       SwarmTopology,
        security:       SwarmSecurityManager,
        config:         Optional[HeartbeatConfig] = None,
        send_transport: Optional[Callable[[bytes], None]] = None,
        battery_fn:     Callable[[], float] = lambda: 100.0,
    ) -> None:
        self._node           = local_node
        self._topology       = topology
        self._security       = security
        self._cfg            = config or HeartbeatConfig.from_env()
        self._send_transport = send_transport
        self._battery_fn     = battery_fn

        self._liveness_map: Dict[str, NodeLivenessState] = {}
        self._events:       List[HeartbeatEvent]        = []
        self._lock                                        = threading.RLock()

        self._sequence       = 0
        self._running        = False

        self._send_timer:  Optional[threading.Timer] = None
        self._check_timer: Optional[threading.Timer] = None

        self._stat_sent      = 0
        self._stat_received  = 0
        self._stat_timeouts  = 0

        _logger.info("HeartbeatManager initialised for drone=%s", local_node.drone_id)

    # ------------------------------------------------------------------
    # Lifecycle Controls
    # ------------------------------------------------------------------

    def start(self) -> None:
        """Starts periodic heartbeat transmission and liveness auditing."""
        with self._lock:
            if self._running:
                return
            self._running = True
            self._send_heartbeat_locked()
            self._schedule_next_heartbeat()
            self._schedule_next_check()
            _logger.info("HeartbeatManager started for %s", self._node.drone_id)

    def stop(self) -> None:
        """Stops heartbeat timers cleanly."""
        with self._lock:
            self._running = False
            if self._send_timer:
                self._send_timer.cancel()
                self._send_timer = None
            if self._check_timer:
                self._check_timer.cancel()
                self._check_timer = None
            _logger.info("HeartbeatManager stopped for %s", self._node.drone_id)

    def is_running(self) -> bool:
        """Returns True if heartbeat timers are active."""
        with self._lock:
            return self._running

    # ------------------------------------------------------------------
    # Transmission (Timer-Chain)
    # ------------------------------------------------------------------

    def _schedule_next_heartbeat(self) -> None:
        """Schedules the next heartbeat transmission timer."""
        if not self._running:
            return
        self._send_timer = threading.Timer(
            self._cfg.interval_sec, self._on_send_timer
        )
        self._send_timer.daemon = True
        self._send_timer.start()

    def _on_send_timer(self) -> None:
        """Timer callback that transmits a heartbeat and reschedules."""
        try:
            self._send_heartbeat()
        except Exception as exc:
            _logger.warning("Error sending heartbeat: %s", exc)
        finally:
            with self._lock:
                if self._running:
                    self._schedule_next_heartbeat()

    def _send_heartbeat_locked(self) -> None:
        """Internal helper to construct and send a heartbeat message while lock is managed safely."""
        seq = self._sequence
        self._sequence = (self._sequence + 1) & 0xFFFF
        self._stat_sent += 1

        msg = HeartbeatMessage(
            sequence=seq,
            flags=0,
            drone_id=str(self._node.drone_id),
            role=self._node.role.name,
            status=self._node.state.name,
            battery_voltage=self._battery_fn(),
            cpu_load=0.0,
        )

        wire_bytes = msg.to_wire_message().serialize()

        if self._send_transport:
            try:
                self._send_transport(wire_bytes)
            except Exception as exc:
                _logger.warning("Transport error sending heartbeat: %s", exc)

        self._emit(HeartbeatEventType.HEARTBEAT_SENT, drone_id=self._node.drone_id)

    def _send_heartbeat(self) -> None:
        """Constructs and sends a heartbeat message."""
        with self._lock:
            self._send_heartbeat_locked()

    # ------------------------------------------------------------------
    # Heartbeat Reception
    # ------------------------------------------------------------------

    def process_heartbeat(self, msg: HeartbeatMessage) -> None:
        """Processes an incoming HeartbeatMessage, updating liveness metrics.

        Args:
            msg: The parsed ``HeartbeatMessage`` instance.
        """
        sender_id = msg.drone_id
        now = time.monotonic()

        with self._lock:
            self._stat_received += 1
            liveness = self._liveness_map.get(sender_id)

            if liveness is None:
                liveness = NodeLivenessState(drone_id=sender_id, last_seen=now)
                self._liveness_map[sender_id] = liveness

            # Out-of-order / Duplicate check
            if liveness.last_sequence != -1:
                if msg.sequence == liveness.last_sequence:
                    _logger.debug("Duplicate heartbeat from %s (seq=%d)", sender_id, msg.sequence)
                    return
                elif msg.sequence < liveness.last_sequence and (liveness.last_sequence - msg.sequence) < 32768:
                    _logger.warning("Out-of-order heartbeat from %s (seq=%d < last=%d)",
                                   sender_id, msg.sequence, liveness.last_sequence)
                    liveness.total_dropped += 1
                    return

            was_unreachable = liveness.is_unreachable

            # Update metrics
            liveness.last_seen = now
            liveness.last_sequence = msg.sequence
            liveness.missed_count = 0
            liveness.total_received += 1
            liveness.is_unreachable = False

            self._emit(HeartbeatEventType.HEARTBEAT_RECEIVED, drone_id=sender_id)

            if was_unreachable:
                _logger.info("Node %s recovered and is reachable again", sender_id)
                self._emit(HeartbeatEventType.NODE_RECOVERED, drone_id=sender_id)
                try:
                    target_node = self._topology.get_node(sender_id)
                    target_node.mark_online()
                except Exception:
                    pass

    # ------------------------------------------------------------------
    # Timeout Audit & Liveness Check
    # ------------------------------------------------------------------

    def _schedule_next_check(self) -> None:
        """Schedules the next liveness audit check."""
        if not self._running:
            return
        self._check_timer = threading.Timer(
            self._cfg.check_interval_sec, self._on_check_timer
        )
        self._check_timer.daemon = True
        self._check_timer.start()

    def _on_check_timer(self) -> None:
        """Timer callback that executes liveness check and reschedules."""
        try:
            self._check_liveness()
        except Exception as exc:
            _logger.warning("Error during liveness check: %s", exc)
        finally:
            with self._lock:
                if self._running:
                    self._schedule_next_check()

    def _check_liveness(self) -> None:
        """Audits all monitored nodes and handles timeouts."""
        now = time.monotonic()
        timed_out_drones: List[str] = []

        with self._lock:
            for drone_id, state in self._liveness_map.items():
                if state.is_unreachable:
                    continue

                elapsed = now - state.last_seen
                if elapsed > self._cfg.timeout_sec:
                    state.missed_count += 1
                    if state.missed_count >= self._cfg.max_missed:
                        state.is_unreachable = True
                        self._stat_timeouts += 1
                        timed_out_drones.append(drone_id)

        # Handle side-effects outside of liveness map lock iterations
        for drone_id in timed_out_drones:
            _logger.warning("Node %s timed out (no heartbeat for %.1f s)", drone_id, self._cfg.timeout_sec)

            with self._lock:
                self._emit(HeartbeatEventType.NODE_TIMEOUT, drone_id=drone_id)

            # Update topology status
            try:
                target_node = self._topology.get_node(drone_id)
                target_node.mark_offline()
            except Exception as exc:
                _logger.debug("Failed to mark node %s offline in topology: %s", drone_id, exc)

            # Expire security session
            try:
                self._security.expire_session(drone_id)
                with self._lock:
                    self._emit(HeartbeatEventType.SESSION_EXPIRED, drone_id=drone_id)
            except Exception as exc:
                _logger.warning("Error expiring session for %s: %s", drone_id, exc)

    # ------------------------------------------------------------------
    # Event Management & Statistics
    # ------------------------------------------------------------------

    def drain_events(self) -> List[HeartbeatEvent]:
        """Returns and clears all pending heartbeat events (thread-safe)."""
        with self._lock:
            events = list(self._events)
            self._events.clear()
            return events

    def statistics(self) -> Dict[str, float | int]:
        """Returns current runtime heartbeat statistics."""
        with self._lock:
            active_count = sum(1 for s in self._liveness_map.values() if not s.is_unreachable)
            total_rx = sum(s.total_received for s in self._liveness_map.values())
            total_drop = sum(s.total_dropped for s in self._liveness_map.values())
            total_pkt = total_rx + total_drop
            loss_rate = (total_drop / total_pkt * 100.0) if total_pkt > 0 else 0.0

            rtts = [s.rtt_estimate for s in self._liveness_map.values() if s.rtt_estimate > 0]
            avg_rtt = (sum(rtts) / len(rtts)) if rtts else 0.0

            return {
                "heartbeats_sent": self._stat_sent,
                "heartbeats_received": self._stat_received,
                "timeouts": self._stat_timeouts,
                "packet_loss_pct": loss_rate,
                "active_neighbors": active_count,
                "average_rtt": avg_rtt,
            }

    def _emit(self, event_type: HeartbeatEventType, drone_id: str = "", extra: str = "") -> None:
        """Appends an event to the queue (caller must ensure thread safety or call inside lock)."""
        self._events.append(HeartbeatEvent(event_type=event_type, drone_id=drone_id, extra=extra))
